services:
  mysql80:
    image: mysql:8.0
    networks:
      - hi_net
    env_file: ./.env
    ports:
      - "3307:3306"
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-intitdb.d
    restart: always
  
  backend:
    build:
      dockerfile: ./backend/Dockerfile
    env_file: ./backend/app/.env
    networks:
      - hi_net
    ports:
      - "8000:8000"
    depends_on:
      - mysql80
    restart: always

networks:
  hi_net:
    driver: bridge