  on: 
    push: 
      branches: ["main"]

  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        # GitHub 저장소의 소스코드를 CI러너(GitHub Actions서버)로 다운로드하는 단계
        # 이 부분이 없으면 러너에 코드가 없어서 이후 비동기적(rscync)로 보낼이 파일이 없게된다.

        - name: SSH설정
          uses: webfactory/ssh-agent@v0.5.4
          # GitHub Secrets에 저장해둔 SSH개인키(PRIVATE_KEY)를 CI러너의 SSH에이전트에 등록하는 단계
          with:
              ssh-private-key: ${{  secrets.PRIVATE_KEY  }}

        # 변경된 파일만 EC2에 동기화
        -  name: 변경된 파일만 EC2에 동기화(rsync)
           run: |
             rsync -avz --delete \
              -e "ssh -o StrictHostKeyChecking=no" \
              --exclude '.git' \
              --exclude '.venv' \
              --exclude 'pycache' \
              --exclude '.pyc' \
              --exclude '.pyo' \
              --exclude 'db/data' \
              ./ ubuntu@${{ secrets.HOST }}:/home/ubuntu/ex0325_fastapi/
          # -a (archive)  :  파일의 권한, 소유자, 차임스탬프 등 메타데이처를 그대로 유지하면서 복사한다. 하위디랙토리도 포함
          # -v (verbose)  :  어떤파일이 전송되는지 log에 출력한다.
          # -z (compress)  :  전송 중 데이터를 압축해서 네트워크 트래픽을 줄여줌
          # --delete  :  로컬에서 삭제된 파일이 있으면 EC2에서도 삭제
          # -E "ssh -o StrictHostKeyChecking=on"  :  rsync가 cancel-timeout-minutes: SSH로 연결할 때 호스트 키 확인을 건너뛰도록 함

        - name: EC2 접속 및 Docker Compose 재빌드
          run: |
            ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.HOST }} << 'EOF'
              cd /home/ubuntu/ex0325_fastapi
              mkdir -p db/
              docker compose down
              docker compose up -d --build
            EOF
